SIAProjeto/ViewModels/TiposUtilizadorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using SIAProjeto.Models;

namespace SIAProjeto.ViewModels
{
    public class TiposUtilizadorViewModel
    {
        private TipoUtilizador tipoUtilizador;
        private List<Permissao_TipoUtilizador> permissoesTipoUtilizadorList;
        private List<Permissao> permissoesList;

        public TipoUtilizador TipoUtilizador
        {
            get
            {
                return tipoUtilizador;
            }

            set
            {
                tipoUtilizador = value;
            }
        }

        public List<Permissao_TipoUtilizador> PermissoesTipoUtilizadorList
        {
            get
            {
                return permissoesTipoUtilizadorList;
            }

            set
            {
                permissoesTipoUtilizadorList = value;
            }
        }

        public List<Permissao> PermissoesList
        {
            get
            {
                return permissoesList;
            }

            set
            {
                permissoesList = value;
            }
        }

        public TiposUtilizadorViewModel()
        {
            tipoUtilizador = new TipoUtilizador();
            permissoesTipoUtilizadorList = new List<Permissao_TipoUtilizador>();
            permissoesList = new List<Permissao>();
        }
    }
}

SIAProjeto/Controllers/TiposUtilizadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using SIAProjeto.Filters;
using SIAProjeto.Models;
using SIAProjeto.ViewModels;

namespace SIAProjeto.Controllers
{
    [RequireHttps]
    [LoginActionFilter]
    [TiposUtilizadorPermissaoActionFilter]
    public class TiposUtilizadorController : Controller
    {
        private DataClassesDBMainDataContext db;

        public TiposUtilizadorController()
        {
            db = new DataClassesDBMainDataContext();
        }

        public ActionResult Index()
        {
            return View(db.TipoUtilizadors);
        }

        public ActionResult Details(int id)
        {
            //Compõe o ViewModel para a página de detalhes do tipo de utiizador
            TiposUtilizadorViewModel detailsViewModel = new TiposUtilizadorViewModel();

            detailsViewModel.TipoUtilizador = db.TipoUtilizadors.Single(t => t.idTipoUtilizador == id);         

            List<Permissao_TipoUtilizador> permissoesTipoUtilizadorList = db.Permissao_TipoUtilizadors.Where(pt => pt.idTipoUtilizador == id).ToList();

            foreach(Permissao_TipoUtilizador pt in permissoesTipoUtilizadorList)
            {
                detailsViewModel.PermissoesList.Add(db.Permissaos.Single(p => p.idPermissao == pt.idPermissao));
            }

            return View(detailsViewModel);
        }

        public ActionResult Create()
        {
            TiposUtilizadorViewModel createViewModel = new TiposUtilizadorViewModel();
            createViewModel.PermissoesList = db.Permissaos.ToList();

            return View(createViewModel);
        }

        [HttpPost]
        public ActionResult Create(FormCollection dadosTipoUtilizador)
        {
            //Verifica cada dado introduzido pelo utilizador por inconsistências (se os campos estão preenchidos, se os campos são válidos, etc.)
            if (string.IsNullOrEmpty(dadosTipoUtilizador["TipoUtilizador.nome"]) == true)
            {
                ModelState.AddModelError("TipoUtilizador.nome", "Tem de introduzir um nome para o novo tipo de utilizador!");
            }
            else
            {
                //Se já existe um tipo de utilizador com o nome introduzido, retorna erro
                if (db.TipoUtilizadors.SingleOrDefault(t => t.nome == dadosTipoUtilizador["nome"]) != default(TipoUtilizador))
                {
                    ModelState.AddModelError("TipoUtilizador.nome", "Um tipo de utilizador com este nome já se encontra criado!");
                }
            }

            if(ModelState.IsValid == true)
            {
                TipoUtilizador newTipoUtilizador = new TipoUtilizador();

                newTipoUtilizador.nome = dadosTipoUtilizador["TipoUtilizador.nome"];

                db.TipoUtilizadors.InsertOnSubmit(newTipoUtilizador);

                db.SubmitChanges();

                foreach(Permissao p in db.Permissaos)
                {
                    //Visto que o ASP.NET MVC faz umas coisas esquisitas com as checkboxes, este workaround certifica que a checkbox de cada permissão é corretamente validada
                    if (dadosTipoUtilizador[string.Concat("permissao", p.idPermissao)].Contains("true") == true)
                    {
                        Permissao_TipoUtilizador newPermissaoTipoUtilizador = new Permissao_TipoUtilizador();

                        newPermissaoTipoUtilizador.idTipoUtilizador = newTipoUtilizador.idTipoUtilizador;
                        newPermissaoTipoUtilizador.idPermissao = p.idPermissao;

                        db.Permissao_TipoUtilizadors.InsertOnSubmit(newPermissaoTipoUtilizador);
                    }
                }

                db.SubmitChanges();

                return RedirectToAction("Index");
            }
            else
            {
                TiposUtilizadorViewModel createViewModel = new TiposUtilizadorViewModel();

                createViewModel.PermissoesList = db.Permissaos.ToList();

                return View(createViewModel);
            }
        }

        public ActionResult Edit(int id)
        {
            //Compõe o ViewModel para a página de edição do tipo de utiizador
            TiposUtilizadorViewModel editViewModel = new TiposUtilizadorViewModel();

            editViewModel.TipoUtilizador = db.TipoUtilizadors.Single(t => t.idTipoUtilizador == id);
            editViewModel.PermissoesTipoUtilizadorList = db.Permissao_TipoUtilizadors.Where(pt => pt.idTipoUtilizador == id).ToList();
            editViewModel.PermissoesList = db.Permissaos.ToList();

            return View(editViewModel);
        }

        [HttpPost]
        public ActionResult Edit(FormCollection dadosTipoUtilizador, int id)
        {
            //Obtém, de acordo com o ID, o tipo de utilizador respetivo para editar
            TipoUtilizador editTipoUtilizador = db.TipoUtilizadors.Single(t => t.idTipoUtilizador == id);

            //Verifica cada dado introduzido pelo utilizador por inconsistências (se os campos estão preenchidos, se os campos são válidos, etc.)
            if (string.IsNullOrEmpty(dadosTipoUtilizador["TipoUtilizador.nome"]) == true)
            {
                ModelState.AddModelError("TipoUtilizador.nome", "Tem de introduzir um nome para o novo tipo de utilizador!");
            }
            else
            {
                //Se o nome do tipo de utilizador introduzido não for igual ao que estava, mas se já existe um tipo de utilizador com o novo nome introduzido, retorna erro
                if (editTipoUtilizador.nome != dadosTipoUtilizador["TipoUtilizador.nome"] && db.TipoUtilizadors.SingleOrDefault(t => t.nome == dadosTipoUtilizador["TipoUtilizador.nome"]) != default(TipoUtilizador))
                {
                    ModelState.AddModelError("TipoUtilizador.nome", "Um tipo de utilizador com este nome já se encontra criado!");
                }
            }

            if (ModelState.IsValid == true)
            {
                //Associa os novos dados ao tipo de utilizador
                editTipoUtilizador.nome = dadosTipoUtilizador["TipoUtilizador.nome"];

                //Apaga todas as relações permissão-tipo associadas a este tipo de utilizador particular
                db.Permissao_TipoUtilizadors.DeleteAllOnSubmit(db.Permissao_TipoUtilizadors.Where(pt => pt.idTipoUtilizador == id));
                db.SubmitChanges();

                //Depois das relações apagadas, volta a criar novas relações permissão-tipo, com base nas novas checkboxes seleccionadas
                foreach (Permissao p in db.Permissaos)
                {
                    //Visto que o ASP.NET MVC faz umas coisas esquisitas com as checkboxes, este workaround certifica que a checkbox de cada permissão é corretamente validada
                    if (dadosTipoUtilizador[string.Concat("permissao", p.idPermissao)].Contains("true") == true)
                    {
                        Permissao_TipoUtilizador newPermissaoTipoUtilizador = new Permissao_TipoUtilizador();

                        newPermissaoTipoUtilizador.idTipoUtilizador = editTipoUtilizador.idTipoUtilizador;
                        newPermissaoTipoUtilizador.idPermissao = p.idPermissao;

                        db.Permissao_TipoUtilizadors.InsertOnSubmit(newPermissaoTipoUtilizador);
                    }
                }

                db.SubmitChanges();

                return RedirectToAction("Index");
            }
            else
            {
                //Compõe o ViewModel para a página de edição do tipo de utiizador
                TiposUtilizadorViewModel editViewModel = new TiposUtilizadorViewModel();

                editViewModel.TipoUtilizador = db.TipoUtilizadors.Single(t => t.idTipoUtilizador == id);
                editViewModel.PermissoesTipoUtilizadorList = db.Permissao_TipoUtilizadors.Where(pt => pt.idTipoUtilizador == id).ToList();
                editViewModel.PermissoesList = db.Permissaos.ToList();

                return View(editViewModel);
            }
        }

        public ActionResult Delete(int id)
        {
            //Compõe o ViewModel para a página de eliminação do tipo de utiizador
            TiposUtilizadorViewModel deleteViewModel = new TiposUtilizadorViewModel();

            deleteViewModel.TipoUtilizador = db.TipoUtilizadors.Single(t => t.idTipoUtilizador == id);
            deleteViewModel.PermissoesList = new List<Permissao>();

            List<Permissao_TipoUtilizador> permissoesTipoUtilizadorList = db.Permissao_TipoUtilizadors.Where(pt => pt.idTipoUtilizador == id).ToList();

            foreach (Permissao_TipoUtilizador pt in permissoesTipoUtilizadorList)
            {
                deleteViewModel.PermissoesList.Add(db.Permissaos.Single(p => p.idPermissao == pt.idPermissao));
            }

            return View(deleteViewModel);
        }

        [HttpPost]
        public ActionResult Delete(FormCollection dummy, int id)
        {
            //Primeiro verifica se este tipo de utilizador possui permissões associadas a ele
            //Se possuir, apaga essas mesmas relações
            db.Permissao_TipoUtilizadors.DeleteAllOnSubmit(db.Permissao_TipoUtilizadors.Where(pt => pt.idTipoUtilizador == id));

            //Depois de todas as relações apagadas, elimina o próprio tipo de utilizador
            db.TipoUtilizadors.DeleteOnSubmit(db.TipoUtilizadors.Single(t => t.idTipoUtilizador == id));

            db.SubmitChanges();

            return RedirectToAction("Index");
        }
    }
}

SIAProjeto/Views/TiposUtilizador/Create.cshtml
@model SIAProjeto.ViewModels.TiposUtilizadorViewModel

@{
    ViewBag.Title = "Criar Novo Tipo de Utilizador";
}

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Criar Novo Tipo de Utilizador</h4>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="white-box">
                <div class="form-horizontal form-material">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.Label("Nome", htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.Editor("nome", new { htmlAttributes = new { @class = "form-control form-control-line" } })
                            @Html.ValidationMessage("nome", "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="submit" value="Criar Novo Tipo de Utilizador" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="white-box">
                <h3 class="box-title">Permissões Disponíveis</h3>

                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayName("Nome")
                                </th>
                                <th>
                                    @Html.DisplayName("Descrição")
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.PermissoesList)
                            {
                                <tr>
                                    <td>
                                        @Html.CheckBox(string.Concat("permissao", item.idPermissao), false, new { htmlAttributes = new { @class = "form-control" } })
                                        &emsp;
                                        @Html.DisplayFor(modelItem => item.nome)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.descricao)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

SIAProjeto/Views/TiposUtilizador/Delete.cshtml
@model SIAProjeto.ViewModels.TiposUtilizadorViewModel

@{
    ViewBag.Title = "Eliminar Tipo de Utilizador";
}

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Eliminar Tipo de Utilizador</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="white-box">
            <h3 class="box-title">Tem a certeza que deseja eliminar este tipo de utilizador?</h3>

            <div class="form-horizontal form-material">
                <div class="form-group">
                    <label class="col-md-12">@Html.DisplayName("Nome")</label>
                    <div class="col-md-12">
                        @Html.DisplayFor(model => model.TipoUtilizador.nome)
                    </div>
                </div>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Eliminar" class="btn btn-success" />
                        @Html.ActionLink("Cancelar", "Index", new { }, new { @class = "btn btn-danger" })
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title">Permissões Concedidas</h3>

            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayName("Nome")
                            </th>
                            <th>
                                @Html.DisplayName("Descrição")
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.PermissoesList)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.descricao)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

SIAProjeto/Views/TiposUtilizador/Details.cshtml
@model SIAProjeto.ViewModels.TiposUtilizadorViewModel

@{
    ViewBag.Title = "Detalhes do Tipo de Utilizador";
}

<div class="row bg-title">
    <div class="col-lg-6 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Detalhes do Tipo de Utilizador</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="white-box">
            <div class="form-horizontal form-material">
                <div class="form-group">
                    <label class="col-md-12">Nome</label>
                    <div class="col-md-12">
                        @Html.DisplayFor(model => model.TipoUtilizador.nome)
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title">Permissões Concedidas</h3>

            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayName("Nome")
                            </th>
                            <th>
                                @Html.DisplayName("Descrição")
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.PermissoesList)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.descricao)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

SIAProjeto/Views/TiposUtilizador/Edit.cshtml
@model SIAProjeto.ViewModels.TiposUtilizadorViewModel

@{
    ViewBag.Title = "Editar Tipo de Utilizador";
}

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Editar Tipo de Utilizador</h4>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="white-box">
                <div class="form-horizontal form-material">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.TipoUtilizador.idTipoUtilizador)

                    <div class="form-group">
                        <label class="col-md-12">Nome</label>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.TipoUtilizador.nome, new { htmlAttributes = new { @class = "form-control form-control-line" } })
                            @Html.ValidationMessageFor(model => model.TipoUtilizador.nome, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="submit" value="Guardar Tipo de Utilizador" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Permissões Disponíveis</h3>

                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayName("Nome")
                                </th>
                                <th>
                                    @Html.DisplayName("Descrição")
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.PermissoesList)
                            {
                                <tr>
                                    <td>
                                        @if (Model.PermissoesTipoUtilizadorList.SingleOrDefault(pt => pt.idPermissao == item.idPermissao) != null)
                                        {
                                            @Html.CheckBox(string.Concat("permissao", item.idPermissao), true, new { htmlAttributes = new { @class = "form-control" } });
                                        }
                                        else
                                        {
                                            @Html.CheckBox(string.Concat("permissao", item.idPermissao), false, new { htmlAttributes = new { @class = "form-control" } });
                                        }
                                        &emsp;
                                        @Html.DisplayFor(modelItem => item.nome)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.descricao)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

SIAProjeto/Views/TiposUtilizador/Index.cshtml
@model IEnumerable<SIAProjeto.Models.TipoUtilizador>

@{
    ViewBag.Title = "Gestor de Tipos de Utilizador";
}

<div class="row bg-title">
    <div class="col-lg-6 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Gestor de Tipos de Utilizador</h4>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 col-sm-6 col-xs-12">
        <div class="white-box analytics-info">
            <h3 class="box-title">Total de Tipos de Utilizador Disponíveis</h3>
            <ul class="list-inline two-part">
                <li>
                    @*<div id="sparklinedash"></div>*@
                </li>
                <li class="text-right"><i class="ti-arrow-up text-success"></i> <span class="counter text-success">@Model.Count()</span></li>
            </ul>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title">Tipos de Utilizador Disponíveis</h3>

            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayName("Nome")
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nome)
                                </td>
                                <td>
                                    @Html.ActionLink("Editar", "Edit", new { id = item.idTipoUtilizador }) |
                                    @Html.ActionLink("Detalhes", "Details", new { id = item.idTipoUtilizador }) |
                                    @Html.ActionLink("Eliminar", "Delete", new { id = item.idTipoUtilizador })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <div class="form-actions no-color">
                @using (Html.BeginForm("Create", "TiposUtilizador", FormMethod.Get))
                {
                    @Html.AntiForgeryToken()

                    <input type="submit" value="Criar Novo Tipo de Utilizador" class="btn btn-success" />
                }
            </div>

        </div>
    </div>
</div>