SIAProjeto/ViewModels/TecnicasViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using SIAProjeto.Models;

namespace SIAProjeto.ViewModels
{
    public class TecnicasViewModel
    {
        private List<Tecnica> tecnicasList;
        private List<Quadrante_Tecnica> quadrantesTecnicaList;
        private List<Quadrante> quadrantesList;
        private List<Pergunta_Quadrante> perguntasQuadrantesList;
        private List<Pergunta> perguntasList;

        private string[] perguntaImportancias;

        public List<Tecnica> TecnicasList
        {
            get
            {
                return tecnicasList;
            }

            set
            {
                tecnicasList = value;
            }
        }

        public List<Quadrante_Tecnica> QuadrantesTecnicaList
        {
            get
            {
                return quadrantesTecnicaList;
            }

            set
            {
                quadrantesTecnicaList = value;
            }
        }

        public List<Quadrante> QuadrantesList
        {
            get
            {
                return quadrantesList;
            }

            set
            {
                quadrantesList = value;
            }
        }

        public List<Pergunta_Quadrante> PerguntasQuadrantesList
        {
            get
            {
                return perguntasQuadrantesList;
            }

            set
            {
                perguntasQuadrantesList = value;
            }
        }

        public List<Pergunta> PerguntasList
        {
            get
            {
                return perguntasList;
            }

            set
            {
                perguntasList = value;
            }
        }

        public string[] PerguntaImportancias
        {
            get
            {
                return perguntaImportancias;
            }

            set
            {
                perguntaImportancias = value;
            }
        }

        public TecnicasViewModel()
        {
            tecnicasList = new List<Tecnica>();
            quadrantesTecnicaList = new List<Quadrante_Tecnica>();
            quadrantesList = new List<Quadrante>();
            perguntasQuadrantesList = new List<Pergunta_Quadrante>();
            perguntasList = new List<Pergunta>();

            perguntaImportancias = new string[] { "Totalmente sem importância", "Pouca importância", "Importante", "Muito importante", "Totalmente importante" };
        }
    }
}

SIAProjeto/Controllers/TecnicasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using SIAProjeto.Filters;
using SIAProjeto.Models;
using SIAProjeto.ViewModels;

namespace SIAProjeto.Controllers
{
    [RequireHttps]
    [LoginActionFilter] // Não deica que um utilizador não autenticado aceda a este Controlador; 
    [TecnicasPermissaoActionFilter]
    public class TecnicasController : Controller
    {
        private DataClassesDBMainDataContext db;       

        public TecnicasController() // Construtor 
        {
            //ligação à base de dados 
            db = new DataClassesDBMainDataContext();
        }

        // o que vai retornar ma View 
        public ActionResult Index()
        {
            TecnicasViewModel indexViewModel = new TecnicasViewModel();

            indexViewModel.TecnicasList = db.Tecnicas.Where(t => t.idUtilizador == Convert.ToInt32(Session["idUtilizadorAutenticado"])).ToList();
            indexViewModel.QuadrantesList = db.Quadrantes.Where(q => q.idUtilizador == Convert.ToInt32(Session["idUtilizadorAutenticado"])).ToList();
            indexViewModel.PerguntasList = db.Perguntas.Where(p => p.idUtilizador == Convert.ToInt32(Session["idUtilizadorAutenticado"])).ToList();

            return View(indexViewModel);
        }

        #region Tecnica
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection dadosNovos)
        {
            //Falta: seleccioncar um quadrante  já feito com perguntas 
            //id selecionado no dropdown já aqui vem; 
            if (string.IsNullOrEmpty(dadosNovos["nome"]) == true)
            {
                ModelState.AddModelError("nome", "Deve Introduzir um nome válido para a técnica");
            }
            
            if (ModelState.IsValid == true)
            {
                Tecnica newTecnica = new Tecnica();

                newTecnica.nome = dadosNovos["nome"];
                newTecnica.idUtilizador = Convert.ToInt32(Session["idUtilizadorAutenticado"]);

                //newTecnica.FlsComplete = dadosQuadrante["FlsComplete"]; 
                //inser a "newTecnica" no conjunto de Dados na base de dados; 
                db.Tecnicas.InsertOnSubmit(newTecnica);
                db.SubmitChanges();

                Quadrante newQuadrante = new Quadrante();

                //db.Quadrantes.Select(Func<Quadrante, idquadrante>);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            TecnicasViewModel detailsViewModel = new TecnicasViewModel();

            detailsViewModel.TecnicasList.Add(db.Tecnicas.Single(t => t.idTecnica == id));

            return View(detailsViewModel);
        }

        public ActionResult Edit(int id)
        {
            TecnicasViewModel editViewModel = new TecnicasViewModel();

            //A técnica que nós queremos é a técnica correspondente ao ID passado como parâmetro
            editViewModel.TecnicasList.Add(db.Tecnicas.Single(t => t.idTecnica == id));
            editViewModel.QuadrantesTecnicaList = db.Quadrante_Tecnicas.Where(qt => qt.idTecnica == id).ToList();
            editViewModel.QuadrantesList = db.Quadrantes.ToList();
            editViewModel.PerguntasQuadrantesList = db.Pergunta_Quadrantes.ToList();
            editViewModel.PerguntasList = db.Perguntas.ToList();   

            return View(editViewModel);
        }

        [HttpPost]
        public ActionResult Edit(FormCollection dadosNovos, int id)
        {
            //Verifica cada dado introduzido pelo utilizador por inconsistências (se os campos estão preenchidos, se os campos são válidos, etc.)
            if (string.IsNullOrEmpty(dadosNovos["nome"]) == true)
            {
                ModelState.AddModelError("nome", "Tem que preencher o campo do nome da técnica!");
            }

            //Se os dados introduzidos estiverem válidos, atualiza a técnica pretendida com esses mesmos dados
            //Depois submete as alterações na base de dados
            if (ModelState.IsValid == true)
            {
                Tecnica editTecnica = db.Tecnicas.Single(t => t.idTecnica == id);         

                editTecnica.nome = dadosNovos["nome"];

                db.SubmitChanges();

                return RedirectToAction("Index");
            }
            else
            {
                TecnicasViewModel editViewModel = new TecnicasViewModel();

                //A técnica que nós queremos é a técnica correspondente ao ID passado como parâmetro
                editViewModel.TecnicasList.Add(db.Tecnicas.Single(t => t.idTecnica == id));
                editViewModel.QuadrantesTecnicaList = db.Quadrante_Tecnicas.Where(qt => qt.idTecnica == id).ToList();
                editViewModel.QuadrantesList = db.Quadrantes.ToList();
                editViewModel.PerguntasQuadrantesList = db.Pergunta_Quadrantes.ToList();
                editViewModel.PerguntasList = db.Perguntas.ToList();

                return View(editViewModel);
            }
        }

        public ActionResult Delete(int id)
        {
            TecnicasViewModel deleteViewModel = new TecnicasViewModel();

            deleteViewModel.TecnicasList.Add(db.Tecnicas.Single(t => t.idTecnica == id));
            deleteViewModel.QuadrantesTecnicaList.AddRange(db.Quadrante_Tecnicas.Where(qt => qt.idTecnica == id));

            foreach(Quadrante_Tecnica qt in deleteViewModel.QuadrantesTecnicaList)
            {
                deleteViewModel.QuadrantesList.Add(db.Quadrantes.Single(q => q.idQuadrante == qt.idQuadrante));
            }

            return View(deleteViewModel);
        }

        [HttpPost]
        public ActionResult Delete(FormCollection dummy, int id)
        {
            db.Quadrante_Tecnicas.DeleteAllOnSubmit(db.Quadrante_Tecnicas.Where(qt => qt.idTecnica == id));
            db.Tecnicas.DeleteOnSubmit(db.Tecnicas.Single(t => t.idTecnica == id));
            db.SubmitChanges();

            return RedirectToAction("Index"); 
        }
        #endregion

        #region Quadrante
        public ActionResult DetailsQuadrante(int id)
        {
            TecnicasViewModel detailsQuadranteViewModel = new TecnicasViewModel();

            detailsQuadranteViewModel.QuadrantesTecnicaList = db.Quadrante_Tecnicas.Where(qt => qt.idQuadrante == id).ToList();

            foreach (Quadrante_Tecnica qt in detailsQuadranteViewModel.QuadrantesTecnicaList)
            {
                detailsQuadranteViewModel.TecnicasList.Add(db.Tecnicas.Single(t => t.idTecnica == qt.idTecnica));
            }

            detailsQuadranteViewModel.QuadrantesList.Add(db.Quadrantes.Single(q => q.idQuadrante == id));
            detailsQuadranteViewModel.PerguntasQuadrantesList = db.Pergunta_Quadrantes.Where(pq => pq.idQuadrante == id).ToList();

            foreach (Pergunta_Quadrante pq in detailsQuadranteViewModel.PerguntasQuadrantesList)
            {
                detailsQuadranteViewModel.PerguntasList.Add(db.Perguntas.Single(p => p.idPergunta == pq.idPergunta));
            }

            return View(detailsQuadranteViewModel);
        }

        public ActionResult CreateQuadrante()
        {
            TecnicasViewModel createQuadranteViewModel = new TecnicasViewModel();

            createQuadranteViewModel.QuadrantesList.Add(new Quadrante());
            createQuadranteViewModel.PerguntasList = db.Perguntas.ToList();

            return View(createQuadranteViewModel);
        }

        [HttpPost]
        public ActionResult CreateQuadrante(FormCollection dadosQuadrante)
        {
            if(string.IsNullOrEmpty(dadosQuadrante["nome"]) == true)
            {
                ModelState.AddModelError("nome", "Tem que preencher o campo do nome do quadrante!");
            }

            if(ModelState.IsValid == true)
            {
                Quadrante newQuadrante = new Quadrante();

                newQuadrante.nome = dadosQuadrante["nome"];
                newQuadrante.idUtilizador = Convert.ToInt32(Session["idUtilizadorAutenticado"]);

                db.Quadrantes.InsertOnSubmit(newQuadrante);
                db.SubmitChanges();

                foreach (Pergunta p in db.Perguntas)
                {
                    //Visto que o ASP.NET MVC faz umas coisas esquisitas com as checkboxes, este workaround certifica que a checkbox de cada pergunta é corretamente validada
                    if (dadosQuadrante[string.Concat("pergunta", p.idPergunta)].Contains("true") == true)
                    {
                        Pergunta_Quadrante newPerguntaQuadrante = new Pergunta_Quadrante();

                        newPerguntaQuadrante.idPergunta = p.idPergunta;
                        newPerguntaQuadrante.idQuadrante = newQuadrante.idQuadrante;

                        db.Pergunta_Quadrantes.InsertOnSubmit(newPerguntaQuadrante);
                    }
                }

                db.SubmitChanges();

                return RedirectToAction("Index");
            }
            else
            {
                TecnicasViewModel createQuadranteViewModel = new TecnicasViewModel();

                createQuadranteViewModel.QuadrantesList.Add(new Quadrante());
                createQuadranteViewModel.PerguntasList = db.Perguntas.ToList();

                return View(createQuadranteViewModel);
            }
        }

        public ActionResult EditQuadrante(int id)
        {
            TecnicasViewModel editQuadranteViewModel = new TecnicasViewModel();

            editQuadranteViewModel.QuadrantesList.Add(db.Quadrantes.Single(q => q.idQuadrante == id));
            editQuadranteViewModel.PerguntasQuadrantesList = db.Pergunta_Quadrantes.Where(pq => pq.idQuadrante == id).ToList();
            editQuadranteViewModel.PerguntasList = db.Perguntas.ToList();

SIAProjeto/Views/Tecnicas/CreatePergunta.cshtml
@model SIAProjeto.Models.Pergunta

@{
    ViewBag.Title = "Nova Pergunta";
}

<div class="row bg-title">
    <div class="col-lg-6 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Nova Pergunta</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="white-box">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal form-material">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.Label("Texto", htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.texto, new { htmlAttributes = new { @class = "form-control form-control-line" } })
                            @Html.ValidationMessageFor(model => model.texto, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Grau de Importância", htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.importancia, new { htmlAttributes = new { @class = "form-control form-control-line" } })
                            @Html.ValidationMessageFor(model => model.importancia, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="submit" value="Criar Pergunta" class="btn btn-success" />
                            <a href="/Tecnicas/Index" class="btn btn-danger">Cancelar</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SIAProjeto/Views/Tecnicas/CreateQuadrante.cshtml
@model SIAProjeto.ViewModels.TecnicasViewModel

@{
    ViewBag.Title = "Novo Quadrante";
}

<div class="row bg-title">
    <div class="col-lg-6 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Novo Quadrante</h4>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="white-box">
                <div class="form-horizontal form-material">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.Label("Nome", htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.QuadrantesList.First().nome, new { htmlAttributes = new { @class = "form-control form-control-line" } })
                            @Html.ValidationMessageFor(model => model.QuadrantesList.First().nome, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="submit" value="Criar Quadrante" class="btn btn-success" />
                            @Html.ActionLink("Cancelar", "Index", new { }, new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="white-box">
                <h3 class="box-title">Escolha que Perguntas deseja adicionar a este Quadrante</h3>

                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayName("Texto")
                                </th>
                                <th>
                                    @Html.DisplayName("Grau de Importância")
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.PerguntasList)
                            {
                                <tr>
                                    <td>
                                        @Html.CheckBox(string.Concat("pergunta", item.idPergunta), false, new { htmlAttributes = new { @class = "form-control" } })
                                        &emsp;
                                        @Html.DisplayFor(modelItem => item.texto)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model.PerguntaImportancias[item.importancia])
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SIAProjeto/Views/Tecnicas/Delete.cshtml
@model SIAProjeto.ViewModels.TecnicasViewModel

@{
    ViewBag.Title = "Eliminar Técnica " + Model.TecnicasList.First().nome;
}

<div class="row bg-title">
    <div class="col-lg-6 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Eliminar Técnica @Model.TecnicasList.First().nome</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="white-box">
            <h3 class="box-title">Tem a certeza que deseja eliminar permanentemente esta técnica?</h3>

            <div class="form-horizontal form-material">
                <div class="form-group">
                    <label class="col-md-12">@Html.DisplayName("Nome")</label>
                    <div class="col-md-12">
                        @Html.DisplayFor(model => model.TecnicasList.First().nome)
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-12">@Html.DisplayName("Data de Criação")</label>
                    <div class="col-md-12">
                        @Html.DisplayFor(model => model.TecnicasList.First().dataCriacao)
                    </div>
                </div>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Eliminar" class="btn btn-success" />
                        @Html.ActionLink("Cancelar", "Index", new { }, new { @class = "btn btn-danger" })
                    </div>
                }
            </div>
        </div>
    </div>
</div>

SIAProjeto/Views/Tecnicas/DeletePergunta.cshtml
@model SIAProjeto.ViewModels.TecnicasViewModel

@{
    ViewBag.Title = "Eliminar Pergunta";
}

<div class="row bg-title">
    <div class="col-lg-6 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Eliminar Pergunta</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="white-box">
            <h3 class="box-title">Tem a certeza que deseja eliminar permanentemente esta pergunta?</h3>

            <div class="form-horizontal form-material">
                <div class="form-group">
                    <label class="col-md-12">@Html.DisplayName("Texto")</label>
                    <div class="col-md-12">
                        @Html.DisplayFor(model => Model.PerguntasList.First().texto)
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-12">@Html.DisplayName("Importância")</label>
                    <div class="col-md-12">
                        @Html.DisplayFor(model => Model.PerguntaImportancias[Model.PerguntasList.First().importancia])
                    </div>
                </div>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Eliminar" class="btn btn-success" />
                        @Html.ActionLink("Cancelar", "Index", new { }, new { @class = "btn btn-danger" })
                    </div>
                }
            </div>
        </div>
    </div>
</div>

SIAProjeto/Views/Tecnicas/DeleteQuadrante.cshtml
@model SIAProjeto.ViewModels.TecnicasViewModel

@{
    ViewBag.Title = "Eliminar Quadrante " + Model.QuadrantesList.First().nome;
}

<div class="row bg-title">
    <div class="col-lg-6 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Eliminar Quadrante @Model.QuadrantesList.First().nome</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="white-box">
            <h3 class="box-title">Tem a certeza que deseja eliminar permanentemente este quadrante?</h3>

            <div class="form-horizontal form-material">
                <div class="form-group">
                    <label class="col-md-12">@Html.DisplayName("Nome")</label>
                    <div class="col-md-12">
                        @Html.DisplayFor(model => model.QuadrantesList.First().nome)
                    </div>
                </div>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Eliminar" class="btn btn-success" />
                        @Html.ActionLink("Cancelar", "Index", new { }, new { @class = "btn btn-dagner"} )
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title">Técnicas que Possuem Este Quadrante</h3>

            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayName("Nome")
                            </th>
                            <th>
                                @Html.DisplayName("Data de Criação")
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.TecnicasList)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.dataCriacao)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title">Perguntas Associadas a Este Quadrante</h3>

            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayName("Nome")
                            </th>
                            <th>
                                @Html.DisplayName("Descrição")
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.PerguntasList)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.texto)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => Model.PerguntaImportancias[item.importancia])
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

SIAProjeto/Views/Tecnicas/Edit.cshtml
@model SIAProjeto.ViewModels.TecnicasViewModel

@{
    ViewBag.Title = "Editar Técnica";
}

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Editar Técnica @Model.TecnicasList.First().nome</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="white-box">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal form-material">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.TecnicasList.First().idTecnica)

                    <div class="form-group">
                        @Html.Label("Nome", htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => Model.TecnicasList.First().nome, new { htmlAttributes = new { @class = "form-control form-control-line" } })
                            @Html.ValidationMessageFor(model => Model.TecnicasList.First().nome, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            <a href="/Tecnicas/Index" class="btn btn-danger">Cancelar</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="row">
    @foreach (var qt in Model.QuadrantesTecnicaList)
    {
        <div class="col-sm-6">
            <div class="white-box">
                <h3 class="box-title">Quadrante @Html.DisplayName(Model.QuadrantesList.Single(q => q.idQuadrante == qt.idQuadrante).nome)</h3>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayName("Texto")
                                </th>
                                <th>
                                    @Html.DisplayName("Grau de Importância")
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var pq in Model.PerguntasQuadrantesList.Where(pq => pq.idQuadrante == qt.idQuadrante))
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model.PerguntasList.Single(p => p.idPergunta == pq.idPergunta).texto)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model.PerguntaImportancias[Model.PerguntasList.Single(p => p.idPergunta == pq.idPergunta).importancia])
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

                @using (Html.BeginForm("RemoveQuadrante", "Tecnicas", new { id = qt.idQuadrante_Tecnica }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Remover" class="btn btn-danger" />
                    </div>
                }
            </div>
        </div>
    }
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title">Escolha que Quadrantes deseja adicionar a esta Técnica</h3>
        </div>
    </div>
</div>

<div class="row">
    @foreach (var q in Model.QuadrantesList)
    {
        if (Model.QuadrantesTecnicaList.SingleOrDefault(qt => qt.idQuadrante == q.idQuadrante) == null)
        {
            <div class="col-sm-6">
                <div class="white-box">
                    <h3 class="box-title">Quadrante @Html.DisplayName(q.nome)</h3>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayName("Texto")
                                    </th>
                                    <th>
                                        @Html.DisplayName("Grau de Importância")
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var pq in Model.PerguntasQuadrantesList.Where(pq => pq.idQuadrante == q.idQuadrante))
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => Model.PerguntasList.Single(p => p.idPergunta == pq.idPergunta).texto)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => Model.PerguntaImportancias[Model.PerguntasList.Single(p => p.idPergunta == pq.idPergunta).importancia])
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                    @using (Html.BeginForm("AddQuadrante", "Tecnicas", new { idTecnica = Model.TecnicasList.First().idTecnica, idQuadrante = q.idQuadrante }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Adicionar" class="btn btn-success" />
                        </div>
                    }
                </div>
            </div>
        }
    }
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SIAProjeto/Views/Tecnicas/NotFound.cshtml
@model SIAProjeto.Models.Tecnica

@{
    ViewBag.Title = "NotFound";
}

<h2>NotFound</h2>